# Generated by Django 5.1.5 on 2025-01-31 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.TextField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("province", models.CharField(max_length=50)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("B2B", "Rivenditore"), ("B2C", "privato")],
                        default=("B2C", "privato"),
                        max_length=3,
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("website", "Sito Web"),
                            ("word-of-mouth", "Passaparola"),
                            ("passerby", "Passante"),
                        ],
                        default=("passerby", "Passante"),
                        max_length=25,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
