# Generated by Django 5.1.5 on 2025-02-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customer_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("good", "Good"), ("service", "Service")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "id_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_estimate_done", models.DateField()),
                ("date_estimate_accepted", models.DateField()),
                ("date_sent_order", models.DateField()),
                ("date_received_cdo", models.DateField()),
                ("date_confirmed_order", models.DateField()),
                ("date_arrived_goods", models.DateField()),
                ("date_closed", models.DateField()),
                (
                    "id_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobStage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stage_name", models.CharField(max_length=255)),
                (
                    "position",
                    models.IntegerField(
                        default=models.AutoField(primary_key=True, serialize=False)
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogJobStage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.job"
                    ),
                ),
                (
                    "id_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.jobstage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("q_t", models.IntegerField()),
                ("discount", models.FloatField(default=0.0)),
                (
                    "id_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "id_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feature"
                    ),
                ),
                (
                    "id_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "id_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                (
                    "id_supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.supplier"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="id_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.CreateModel(
            name="Monetization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "id_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feature"
                    ),
                ),
                (
                    "id_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
    ]
