# Generated by Django 5.1.5 on 2025-02-04 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_category_supplier_feature_job_jobstage_logjobstage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="date_arrived_goods",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_closed",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_confirmed_order",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_estimate_accepted",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_estimate_done",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_received_cdo",
        ),
        migrations.RemoveField(
            model_name="job",
            name="date_sent_order",
        ),
        migrations.RemoveField(
            model_name="jobstage",
            name="job",
        ),
        migrations.RemoveField(
            model_name="logjobstage",
            name="status",
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Sconto in percentuale (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
