# Generated by Django 5.1.5 on 2025-02-06 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_job_date_arrived_goods_remove_job_date_closed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="id_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="id_customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="logjobstage",
            old_name="id_job",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="logjobstage",
            old_name="id_stage",
            new_name="stage",
        ),
        migrations.RenameField(
            model_name="monetization",
            old_name="id_product",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="id_job",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="id_product",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="orderdetail",
            old_name="id_feature",
            new_name="feature",
        ),
        migrations.RenameField(
            model_name="orderdetail",
            old_name="id_order",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="id_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="id_supplier",
            new_name="supplier",
        ),
        migrations.RenameField(
            model_name="productfeature",
            old_name="id_feature",
            new_name="feature",
        ),
        migrations.RenameField(
            model_name="productfeature",
            old_name="id_product",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="order",
            name="q_t",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_feature_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="monetization",
            constraint=models.UniqueConstraint(
                fields=("product", "started_at"), name="unique_monetization"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_product_name_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="productfeature",
            constraint=models.UniqueConstraint(
                fields=("feature", "product"), name="unique_product_feature"
            ),
        ),
    ]
