# Generated by Django 5.1.5 on 2025-02-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_customer_created_by_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("B2B", "Rivenditore"), ("B2C", "privato")],
                default=("B2C", "privato"),
                max_length=25,
            ),
        ),
    ]
