# Generated by Django 5.1.5 on 2025-02-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="New Category", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("good", "Good"), ("service", "Service")],
                default="good",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("website", "Sito Web"),
                    ("word-of-mouth", "Passaparola"),
                    ("passerby", "Passante"),
                ],
                default="passerby",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("B2B", "Rivenditore"), ("B2C", "privato")],
                default="B2C",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="province",
            field=models.CharField(default="AQ", max_length=50),
        ),
    ]
