# Generated by Django 5.1.5 on 2025-02-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_job_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.customer"
            ),
        ),
    ]
