# Generated by Django 5.1.5 on 2025-02-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_job_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.customer"
            ),
        ),
    ]
