# Generated by Django 5.1.5 on 2025-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_job_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="stage",
            field=models.CharField(
                choices=[
                    ("estimate done", "Estimate"),
                    ("estimate_accepted", "Estimate accepted"),
                    ("sent_order", "Sent order"),
                    ("received_cdo", "Received CDO"),
                    ("confirmed_order", "Confirmed order"),
                    ("arrived_goods", "Arrived goods"),
                    ("closed", "Closed"),
                ],
                default="estimate done",
                max_length=255,
            ),
        ),
    ]
