# Generated by Django 5.1.5 on 2025-02-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_job_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="referenced_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_category",
                to="api.category",
            ),
        ),
    ]
