# Generated by Django 5.1.5 on 2025-02-24 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_feature_referenced_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                default="Nuova categoria", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="referenced_category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_category",
                to="api.category",
            ),
        ),
    ]
