# Generated by Django 5.1.5 on 2025-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_feature_category_alter_feature_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                default="Nuova caratteristica", max_length=255, null=True
            ),
        ),
    ]
