# Generated by Django 5.1.5 on 2025-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_category_name_alter_feature_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
