# Generated by Django 5.1.5 on 2025-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_feature_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
