# Generated by Django 5.1.5 on 2025-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_product_unit_cost_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Monetization",
        ),
    ]
