openapi: 3.1.0
info:
  title: API del Progetto Django
  version: 1.0.0
  description: Descrizione delle API del progetto Django

servers:
  - url: http://localhost:8000
    description: Server locale di sviluppo

paths:
  /api/customers/:
    get:
      summary: Ottieni la lista dei clienti
      responses:
        "200":
          description: Lista dei clienti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

  /api/token/:
    post:
      summary: Ottieni un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Token JWT ottenuto
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                  refresh:
                    type: string

  /api/token/refresh/:
    post:
      summary: Ottieni un nuovo token JWT utilizzando il token di refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        "200":
          description: Nuovo token JWT ottenuto
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string

  /api-auth/login/:
    post:
      summary: Effettua il login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login effettuato
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /api-auth/logout/:
    post:
      summary: Effettua il logout
      responses:
        "200":
          description: Logout effettuato

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        phone:
          type: string
